version: '3'

services:
  db:
    container_name: atlantic_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'db'
    volumes:
      - db:/var/lib/mysql
    ports:
      - 13306:3306

volumes:
  db:
